import { Geist, Geist_Mono } from "next/font/google";
import { Inconsolata, Jersey_15 } from '@next/font/google';
import { Bona_Nova_SC } from 'next/font/google';

import "./globals.css";
import Navbar from "./components/Navbar/Navbar";

import { Providers } from "./components/Providers";

const bonaNovaSC = Bona_Nova_SC({
  subsets: ['latin'], // Choose the subset you need
  weight: ['400', '700'], // Include the required weights
  style: ['normal', 'italic'], // Add styles as needed
  variable: '--font-bona-nova', // Optional: Custom CSS variable
});

const inconsolata = Inconsolata({
  subsets: ['latin'],
  weight: ['200', '400', '900'], // Add the desired weights
});

const jersey = Jersey_15({
  subsets: ['latin'],
  weight:['400']
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jersey.variable} ${inconsolata.variable} ${bonaNovaSC.variable} antialiased`}
      >
       
        <Providers>
           <Navbar/>
          {children}
          </Providers>
       
      </body>
    </html>
  );
}
