import { Geist, Geist_Mono } from "next/font/google";

import { Bona_Nova_SC } from 'next/font/google';

import "./globals.css";
import Navbar from "./components/Navbar/Navbar";

import { Providers } from "./components/Providers";

const bonaNovaSC = Bona_Nova_SC({
  subsets: ['latin'], 
  weight: ['400', '700'], 
  style: ['normal', 'italic'], 
  variable: '--font-bona-nova', 
});



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  ${bonaNovaSC.variable} antialiased`}
      >
       
        <Providers>
           <Navbar/>
          {children}
          </Providers>
       
      </body>
    </html>
  );
}
